name: publish
on:
  release:
    types:
      - published 
env:
  NPM_TOKEN: ${{ secrets.npm_token }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo releasing version 1.0 of test
      - uses: actions/checkout@v2
      - run: | 
          npm ci
          npm t
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
