on:
  push:
    branches: [main]
jobs:
  prerelease:
    runs-on: ubuntu-latest
    env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - run: |
            git checkout -b release/${{ steps.package-version.outputs.current-version}}
            npm version prerelease --preid beta  
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: beta
