on:
  push:
    branches: [main]
jobs:
  prerelease:
    runs-on: ubuntu-latest
    env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       GITHUB_USER: Automated Version bumping
       GITHUB_EMAIL: automation@audioeye.com
    steps:
      - name: Setup GIT
        run: |
          git switch -c master
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - run: |
            git checkout -b release/${{ steps.package-version.outputs.current-version}}
            npm version prerelease --preid beta  
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: beta
