on:
  push:
    branches: [main]
jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo all tests passed, bumping version
      - uses: phips28/gh-action-bump-version@master
        with:
          minor-wording: "add,Adds,new"
          major-wording: "MAJOR,cut-major"
          patch-wording: "patch,fixes"
          default: patch
          push: false
      - run: |
          git config --global user.email automation@audioeye.com
          git config --global user.name Automated Version Bump
      - run: npm version prerelease --preid beta -m "prerelease version %s :automation"
        with:
          version: 'prerelease'
          git-tag-version: 'true'
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: beta
