 
 name: Check if it build and passes unit test
 on: 
  pull_request:
    branches: 
      - main
 jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is where you would build it"
  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm t


  
 

