name: Pre PR Checks
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is where you would build it"
  unit_tests:
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm t
      - name: branch naming rules
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/TOOLS\-\d\d\d\d?' # Regex the branch should match. This example enforces grouping eg. bug/TOOLS-1911
          allowed_prefixes: "feature,stable,fix, e2e, testing" # All branches should start with the given prefix
          ignore: master,develop # Ignore exactly matching branch names from convention
          min_length: 5 # Min length of the branch name
          max_length: 20 # Max length of the branch
      - name: PR label
        if: ${{ github.event.type }} == opened
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
  versioning: 
    runs-on: ubuntu-latest  
    needs: unit_tests
    steps: 
    - uses: actions/checkout@v2
    - run: echo all tests passed, bumping version
    - uses: phips28/gh-action-bump-version@master
      with:
        minor-wording: "add,Adds,new"
        major-wording: "MAJOR,cut-major"
        patch-wording: "patch,fixes"
        default: patch
